### ISSUE TITLE
Win32Exception thrown when GTA processes destroyed using controller

### ISSUE THREAD

**Issue by BradF-99** [BradF-99/GTAPanicButton#4]
This only seems to happen when the GTA processes are destroyed. This only affects the features-controller-support branch at the moment and I would like to fix it before it is merged. It also seems to trigger the worker twice, as the TTS runs twice - maybe it is something to do with the controller polling?

Resources:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=netframework-4.8

**Comment by AlexB6773** [comment]
Check for any instances of the program open before you kill 🤗.

**Comment by BradF-99** [comment]
I've done that and also made the thread sleep for 5 seconds so the controller can't trigger it twice. Thanks, that seems to have fixed it!
