### ISSUE TITLE
Looks great but how to use 

### ISSUE THREAD

**Issue by Wicked13-coder** [BradF-99/GTAPanicButton#8]
Hey, This is by far the best code as per me, but i can't sort out how to use it, as I am new to github, and I am feeling sad as I cant run it... LOL Looking forward to your solution.

**Comment by BradF-99** [comment]
Hi @Wicked13-coder sorry for the late response! 

To run the Panic Button, all you need to do is click the latest release on the side of the repository.  
![image](https://user-images.githubusercontent.com/37586752/94896471-e8c70d80-04d0-11eb-8e17-4de6ea4cdd5f.png)  

In that page there is a link to the executable file - just download that and run it. If you have any further issues, don't hesitate to contact me.

**Comment by Wicked13-coder** [comment]
I still can not find the executable file, although I have downloaded the RAR File but still there was no executable file in that, I am attaching a screenshot of the RAR, also its not even in the GTAPanicButton..
![2020-10-05](https://user-images.githubusercontent.com/71885833/95080457-c08c1880-0735-11eb-8520-bccf6c9dd404.png)

**Comment by BradF-99** [comment]
Hi,

You can get the latest release by going to the main repository page, and clicking the Releases button on the side.

<img width="1277" alt="Screenshot of repository" src="https://user-images.githubusercontent.com/37586752/95089748-d4507280-0767-11eb-915c-ae4c7c55f02e.png">

Once you've done this, scroll down and click on the GTAPanicButton.exe link.

<img width="1277" alt="Screenshot of download page" src="https://user-images.githubusercontent.com/37586752/95089687-c3076600-0767-11eb-8b57-cc3ea39c08a1.png">

In case this still doesn't work, [click here to download the latest version.](https://github.com/BradF-99/GTAPanicButton/releases/download/b73/GTAPanicButton.exe)

**Comment by Pongooo** [comment]
sorry im am still lost pls help asap urgent

**Comment by AlexB6773** [comment]
Hello, does this work on MS-DOS, thank you

**Comment by Wicked13-coder** [comment]
> Hi,
> 
> You can get the latest release by going to the main repository page, and clicking the Releases button on the side.
> 
> <img alt="Screenshot of repository" width="1277" src="https://user-images.githubusercontent.com/37586752/95089748-d4507280-0767-11eb-915c-ae4c7c55f02e.png">
> 
> Once you've done this, scroll down and click on the GTAPanicButton.exe link.
> 
> <img alt="Screenshot of download page" width="1277" src="https://user-images.githubusercontent.com/37586752/95089687-c3076600-0767-11eb-8b57-cc3ea39c08a1.png">
> 
> In case this still doesn't work, [click here to download the latest version.](https://github.com/BradF-99/GTAPanicButton/releases/download/b73/GTAPanicButton.exe)

Yeah it worked for me... Thanks a lot man.

**Comment by Pongooo** [comment]
no problems glad i fixed the problem 👍
